version: '3.5'
services: 
    debian:
        build:
            context: archivos_docker/debian_config
        container_name: debian
        depends_on: 
            - mysql-server
        ports:
            - 8000:8097
        volumes:
            - ./fuente_codigo:/Aplicaciones/prueba_tecnica
            - /home/bstiven/Documentos/:/Aplicaciones/archivos
        networks:
            - prueba_tecnica_network
        command: tail -f /dev/null
        links:
            - mysql-server:mysql-server
    mysql-server:
        build: 
            context: archivos_docker/mysql_config
        container_name: mysql-server
        ports: 
            - 3520:3306
        environment: 
            TZ: "America/Bogota"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_PASSWORD: ""
        networks: 
            - prueba_tecnica_network

networks: 
    prueba_tecnica_network:
        external: true
